### ISSUE TITLE
[FEAT] 섹션 기반 풀페이지 스크롤링을 구현합니다.

### ISSUE THREAD

**Issue by bbjbc** [Team-4yclingHomerun/4yclinghomerun-client#1]
## 📄 Describe

메인페이지의 섹션을 나누어 섹션 별로 페이지 스크롤링을 구현합니다.

## ☑️ Tasks

- [ ] URL 해시를 통해 특정 섹션으로 직접 이동합니다.
- [ ] 섹션 전환 시 부드러운 애니메이션 효과를 적용합니다. (`framer-motion` 사용)
- [ ] 마우스 휠과 터치 스크린 모두에서 스크롤링이 작동합니다.

## 📋 Ref

Additional information or reference documents.
