### ISSUE TITLE
[FEAT] 메인 페이지의 일부 완성된 기능을 통합 합니다

### ISSUE THREAD

**Issue by HyoKyoungLee** [Team-4yclingHomerun/4yclinghomerun-client#12]
## 📄 Describe

메인 페이지의 각자 팀원이 맡았던 파트를 하나로 통합하는 작업을 합니다.

## ☑️ Tasks

- [x] 히어로 섹션, 온라인 스토어 섹션, 사이드바, 경기 일정, 팀 순위를 메인 페이지에 합칩니다
- [x] 일관적이지 않게 저장되었던 asset 아래의 폴더의 이미지 파일을 정리합니다
- [x] 메인(Home) 페이지에 들어가는 컴포넌트는 home 폴더에 아래에 넣습니다.
- [x] 그외 통일되지 않은 부분들을 수정합니다

## 📋 Ref

- 기존 일관적으로 들어가 있지 않은 asset의 이미지 파일들
![image](https://github.com/user-attachments/assets/ce81771d-92aa-44a0-a08b-098754ab33b4)

- 기존 각각 다른 폴더에 넣어져 있는 메인(Home) 페이지에 들어가는 컴포넌트들
![image](https://github.com/user-attachments/assets/ec07ae86-347b-41e9-b641-1a01cd1e140c)

**Comment by HyoKyoungLee** [comment]
develop 브랜치로 분기하려 작업 완료함(9/10)

**Comment by HyoKyoungLee** [comment]
git flow 준수를 위해서 develop 브랜치를 만들어서 위 작업을 완료하였음 (2024/09/10)
