### ISSUE TITLE
[FEAT] footer 부분을 퍼블리싱합니다.

### ISSUE THREAD

**Issue by bbjbc** [Team-4yclingHomerun/4yclinghomerun-client#17]
## 📄 Describe

footer 섹션을 퍼블리싱합니다.

## ☑️ Tasks

- [x] 현 ktwiz 홈페이지의 푸터 섹션을 구현합니다.
- [x] 그룹사 드롭다운에 애니메이션을 추가합니다.
- [x] `개인정보 처리방침`, `이용약관`, `이메일무단수집거부`를 클릭 시 모달 창에 나타나도록 합니다.

## 📋 Ref

![image](https://github.com/user-attachments/assets/8aed029e-4d35-4c95-920e-62638e0300b0)
