### ISSUE TITLE
[FEAT] 정규 리그 페이지를 퍼블리싱합니다.

### ISSUE THREAD

**Issue by bbjbc** [Team-4yclingHomerun/4yclinghomerun-client#21]
## 📄 Describe

정규 리그 페이지를 퍼블리싱합니다.

## ☑️ Tasks

- [x] 상세 페이지의 레이아웃을 구성합니다.
- [x] 메인페이지에 존재했던 일주일 치 경기 캐러셀을 가져와 사용합니다.
- [x] 아래 달력은 테이블을 사용하여 ui를 개선합니다.
- [x] 달력형 뿐 아닌 리스트형으로 렌더링이 가능하게 합니다.

## 📋 Ref

Additional information or reference documents.
