### ISSUE TITLE
[FEAT] 미완성된 뉴스 & 이벤트 섹션을 퍼블리싱합니다.

### ISSUE THREAD

**Issue by jungkyuYang** [Team-4yclingHomerun/4yclinghomerun-client#23]
## 📄 Describe

저번에 미완성된 뉴스 & 이벤트 섹션을 퍼블리싱합니다.

## ☑️ Tasks

- [x] mock데이터를 만들어서 사용합니다.
- [x] hover시 동작하는 css를 정상적으로 동작하도록 수정합니다.
- [x] `이벤트` 섹션을 프레젠테이션 방식으로 변경합니다.

## 📋 Ref

Additional information or reference documents.
