### ISSUE TITLE
[FEAT] 메인페이지에 경기 일정 및 팀 순위를 퍼블리싱합니다.

### ISSUE THREAD

**Issue by bbjbc** [Team-4yclingHomerun/4yclinghomerun-client#3]
## 📄 Describe

메인페이지에 경기 일정 및 팀 순위를 나타냅니다.

## ☑️ Tasks

- [ ] 경기 일정은 카드 형식으로 캐러셀 형식으로 만듭니다.
- [ ] 경기 일정 안에는 `경기 장소`, `경기 일시`, `두 팀 로고`, `경기 정보 버튼`이 포함됩니다.
- [ ] 경기 일정은 하루 전 경기부터 추후 일주일 간 앞둔 경기를 나타냅니다.
- [ ] 팀 순위는 현재 팀의 순위와 앞 뒤 순위와의 게임차가 나타나도록 합니다.

## 📋 Ref

Additional information or reference documents.
