### ISSUE TITLE
[FEAT] Player페이지에 목록(코칭스탭, 투수, 타자, 응원단)을 퍼블리싱 합니다.

### ISSUE THREAD

**Issue by jungkyuYang** [Team-4yclingHomerun/4yclinghomerun-client#32]
## 📄 Describe

Player페이지에 목록(코칭스탭, 투수, 타자, 응원단)을 퍼블리싱 합니다.

## ☑️ Tasks

- [ ] Player 페이지에 목록들이 카드 형식으로 호출되도록 만듭니다.
- [ ] Player 페이지에 목록별로 검색이 가능하도록 만듭니다.
- [ ] Player 페이지에 목록을 클릭시 상세 페이지가 출력되도록 만듭니다.
- [ ] 상세 페이지에는 fetch한 json항목들이 보여지도록 만듭니다.

## 📋 Ref

https://fay-story.com/entry/Tailwind-CSS-Tailwind-CSS%EB%A1%9C-%EB%8B%A4%EC%96%91%ED%95%9C-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0-3d-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98-bg-gradient-image-url-%EB%B0%98%EC%9D%91%ED%98%95-%EB%94%94%EC%9E%90%EC%9D%B8
