### ISSUE TITLE
[FEAT] 메인페이지에 온라인스토어 상품과 고정 사이드바를 퍼블리싱 합니다.

### ISSUE THREAD

**Issue by hdayeon** [Team-4yclingHomerun/4yclinghomerun-client#4]
## 📄 Describe

메인페이지에 온라인스토어 상품과 우측 고정 사이드바를 퍼블리싱 합니다.

## ☑️ Tasks

- [x] 메인 상품 1개는 크게, 나머지는 같은 크기의 타일 형식으로 만듭니다.
- [x] 상품 이미지 호버 시 상품 이름, 가격이 나옵니다.
- [x] 사이드바는 우측 세로 중앙에 고정되도록 합니다.
- [x] 사이드바 요소는 티켓예매, 사전주차예약, 유투브, 인스타그램 으로 구성합니다.

## 📋 Ref

Additional information or reference documents.
