### ISSUE TITLE
[FEAT] wiz뉴스 상세페이지를 완성합니다.

### ISSUE THREAD

**Issue by hdayeon** [Team-4yclingHomerun/4yclinghomerun-client#48]
## 📄 Describe

뉴스 상세페이지 퍼블리싱과 데이터 페칭을 합니다.

## ☑️ Tasks

- [x] 상세페이지 스타일 퍼블리싱
- [x] 상세페이지 데이터 연동
- [x] 상세페이지 스켈레톤 적용

## 📋 Ref

뉴스 리스트 페이지 깜박이는 이슈도 최대한 핸들링 예정입니다.
