### ISSUE TITLE
[FEAT] 정규 리그 > 순위기록 > 투수/타자기록 페이지를 퍼블리싱합니다

### ISSUE THREAD

**Issue by HyoKyoungLee** [Team-4yclingHomerun/4yclinghomerun-client#54]
## 📄 Describe

- 정규 리그 > 순위기록 > 투수/타자기록 페이지를 퍼블리싱합니다

## ☑️ Tasks

- [ ] 정규 리그 > 순위기록 > 투수/타자기록 페이지를 퍼블리싱합니다
- [ ] 투수/타자 기록 2개의 페이지를 1개의 공통 컴포넌트로 구현하여 코드의 재사용성과 유지보수성을 높입니다
- [ ] 테이블의 검색, 정렬 기능을 구현합니다

## 📋 Ref

- 기존 투수기록 페이지 : https://www.ktwiz.co.kr/game/regular/ranking/pitcher (타자기록 페이지도 UI가 동일함)

![image](https://github.com/user-attachments/assets/bafaa652-2188-4228-91f7-1386f62df2d2)
