### ISSUE TITLE
[FEAT] Player 페이지와 상세 페이지를 구현합니다.

### ISSUE THREAD

**Issue by jungkyuYang** [Team-4yclingHomerun/4yclinghomerun-client#57]
## 📄 Describe

Player 페이지와 상세 페이지를 구현합니다.

## ☑️ Tasks

- [x] 각 페이지별 검색기능을 구현합니다.
- [x] 각 페이지에서 사용되는 카드 컴포넌트를 구현합니다.
- [x] 각 상세페이지에서 사용되는 프로필 컴포넌트를 구현합니다.
- [x] 각 선수 상세페이지에서 사용되는 차트를 구현합니다.

## 📋 Ref

- 없음
