### ISSUE TITLE
[FIX] `DetailPageLayout`, `ScrollToTopButton`에서 발생하는 버그를 수정합니다.

### ISSUE THREAD

**Issue by bbjbc** [Team-4yclingHomerun/4yclinghomerun-client#65]
## 📄 Describe

네비게이션바의 경로를 클릭했을 때는 정상적으로 페이지가 맨 위로 이동하지만, `DetailPageLayout` 컴포넌트(상세 페이지 레이아웃)에서는 탭의 경로를 클릭해도 페이지가 맨 위로 이동하지 않는 버그가 발생했습니다. 이 버그를 수정합니다.

## ☑️ Tasks

- [ ] 탭을 클릭했을 때 페이지가 맨 위로 이동하도록 수정합니다.
- [ ] `구단 연혁` 페이지로 이동 시, `DropTabNavigation`이 현재 위치가 맨 위에 있어도 사라지지 않는 문제를 해결합니다.
- [ ] `구단 연혁` 페이지 이외에 스크롤 부분이 `overflow-hidden`에 의해 네비게이션바에 가려지는 현상을 수정합니다.

## 📋 Ref

1. 탭 클릭 시 페이지가 맨 위로 이동하지 않음

https://github.com/user-attachments/assets/6c0c422b-1937-4fcd-836a-38938c264c8b

2. `구단 연혁` 페이지로 이동 시, `DropTabNavigation`이 페이지의 맨 위에 있어도 사라지지 않음

https://github.com/user-attachments/assets/a2036072-b41f-465d-bc93-33aa88b978f9

3. `구단 연혁` 페이지 이외에 스크롤 부분이 네비게이션바에 가려지는 현상 발생

https://github.com/user-attachments/assets/65a940a1-c28d-419c-9600-b629cf4d7953
