### ISSUE TITLE
[FEAT] KT Wiz 팬들이 소통할 수 있는 단체 채팅 페이지를 퍼블리싱합니다

### ISSUE THREAD

**Issue by HyoKyoungLee** [Team-4yclingHomerun/4yclinghomerun-client#68]
## 📄 Describe

- KT Wiz 팬들이 소통할 수 있는 단체 채팅 페이지를 퍼블리싱합니다

## ☑️ Tasks

- [x] 단체 실시간 채팅방을 퍼블리싱합니다
- [x] 채팅방 상단에 커뮤니티 운영방침 버튼과 모달창을 퍼블리싱합니다
- [x] 기본적으로 메시지 보내기 버튼이 보이지 않다가 input 창에 메시지를 입력하면 button이 나오도록 애니메이션을 구현합니다
- [x] 채팅 메시지가 1명의 사용자가 연속으로 메시지를 입력하면 사용자의 닉네임과 날짜가 중복해서 나오지 않고 1번만 보이도록 구현합니다
- [x] 현재 로그인된 사용자의 메시지의 닉네임은 표기되지 않도록 퍼블리싱합니다

## 📋 Ref

- 채팅방 : 카카오톡, 안드로이드 메시지 화면 등
- 커뮤니티 운영방침 모달 : wizzap
<img src="https://github.com/user-attachments/assets/dd8112b4-5c84-4945-b796-9aa7871a41dc">
