### ISSUE TITLE
[STYLE] 네비게이션 바 구조를 변경합니다.

### ISSUE THREAD

**Issue by bbjbc** [Team-4yclingHomerun/4yclinghomerun-client#69]
## 📄 Describe

`login` 버튼이 네비게이션 바에 삽입되면서 정렬이 맞지 않는 문제를 해결하기 위해 네비게이션 바의 구조를 변경합니다.

## ☑️ Tasks

- [x] `WIZ PARK` 링크 안에 `DIRECTION`을 탭으로 삽입합니다.
- [ ] x축 레이아웃을 더욱 줄입니다.
- [x] `KT WIZ`, `WIZ PARK`, `GAME`   로고   `COMMUNITY`, `PLAYER`, `NEWS`  &nbsp; &nbsp;`LOG IN` 과 같이 만듭니다.

## 📋 Ref

Additional information or reference documents.
