### ISSUE TITLE
[FEAT] 메인페이지에 News 섹션과 이벤트 섹션을 퍼블리싱 합니다.

### ISSUE THREAD

**Issue by jungkyuYang** [Team-4yclingHomerun/4yclinghomerun-client#7]
## 📄 Describe

메인페이지에 News 섹션과 이벤트 섹션을 퍼블리싱 합니다.

## ☑️ Tasks

- [x] News 섹션에는 4개의 카드 형식이 호출 되도록 만듭니다.
- [ ] News 섹션 더보기 버튼 클릭시 news 페이지로 이동합니다.
- [ ] 이벤트 섹션에는 4개의 슬라이드가 출력 되도록 만듭니다.

## 📋 Ref

[News 섹션](https://www.ns-esports.com/#sec5)
