### ISSUE TITLE
[REFACTOR] 커스텀 스크롤바를 구현하여 전반적인 UI를 개선합니다

### ISSUE THREAD

**Issue by HyoKyoungLee** [Team-4yclingHomerun/4yclinghomerun-client#76]
## 📄 Describe

- 커스텀 스크롤바를 구현하여 UI를 개선합니다

## ☑️ Tasks

- [ ] 기본 스크롤바를 보이지 않게 합니다
- [ ] 커스텀 스크롤바를 공용 컴포넌트로 만들어 다양한 컴포넌트에서 사용할 수 있도록 합니다
- [ ] 커스텀 스크롤바 기능
  - [ ] 스크롤바의 기본 기능을 구현합니다
  - [ ] 스크롤이 발생할 때만 스크롤바가 보이도록 합니다
- [ ] DetailLayout, 메인페이지, 테이블 등 스크롤바가 사용되는 곳에 커스텀 스크롤바로 변경합니다 

#### 1️⃣ **UI 안정성  및** **일관성 개선**

- 기본 스크롤바를 사용할 경우, 스크롤바의 너비가 화면 너비에 포함되어 **전체 레이아웃이 왼쪽으로 이동하는 현상**을 발생하는 이슈를 개선할 수 있음
- 커스텀 스크롤바로 **필요할 때만 나타나도록 설정**하여 시각적 복잡도를 줄이고 사용자가 중요한 정보에 더 집중할 수 있음
- 웹사이트의 **디자인 테마나 브랜드 아이덴티티**에 맞춰 스크롤바의 색상, 모양, 크기 등을 커스텀하여 UI 전반에 **일관성**을 부여할 수 있음

#### 2️⃣ 성능 최적화

- 스크롤이 없는 상태에서 스크롤바가 숨겨져 있으면 **불필요한 렌더링 리소스를 줄일 수 있어** 성능 최적화에도 기여할 수 있음

### 기존 스크롤바 사용 UI
- 전체 레이아웃이 왼쪽으로 밀리는 현상이 발생함
- 전반적인 UI의 어울리지 않는 스크롤바 사용으로 UI 일관성을 저해시킴
- 스크롤하지 않는 상태에서 스크롤바가 보여 비교적 주요 정보에 대한 집중력을 떨어트림
![image](https://github.com/user-attachments/assets/759b5f79-0c9e-4842-aaf7-70ba73ae82f9)

### 커스텀 스크롤바 적용 UI
- 스크롤바에 absolute을 적용하여 왼쪽으로 밀리는 현상을 개선함
- 전반적인 UI와 어울리는 스크롤바로 스타일을 변경하여 일관성을 개선시킴
- 스크롤하지 않는 상태에서는 스크롤바가 보이지 않아 사용자가 주요 정보에 집중할 수 있도록 함

![커스텀 스크롤바 구현 영상](https://github.com/user-attachments/assets/8e7e458a-925c-448b-9de8-b1b06664e818)

### 커스텀 스크롤바로 변경 시 단점
- 기본 스크롤바는 마우스로 드래그하여 빠른 스크롤을 할 수 있지만, 위에 설명한 커스텀 스크롤바는 해당 기능이 불가합니다
- 하지만 페이지마다 `ScrollToTopButton` 버튼이 있어 크게 문제되지 않을 것으로 예상됩니다

**Comment by hdayeon** [comment]
너비를 차지하지 않고 보기에 훨씬 깔끔해 보여서 좋습니다.
다만 드래그가 아예 불가능한 걸까요?
아주 치명적이진 않지만 조금 아쉬운 부분이네요!

**Comment by bbjbc** [comment]
드래그가 안된다는건 너무 치명적이라고 생각합니다..

**Comment by HyoKyoungLee** [comment]
@hdayeon @bbjbc 넵 의견 감사합니다. 의견주신 내용을 바탕으로 마우스 드래그 스크롤 기능도 구현하겠습니다.

레퍼런스는 네이버 웨일 스크롤바로 데일리스크럼 때 @jungkyuYang 님이 알려주셨습니다

![2024-10-25 13 52 35](https://github.com/user-attachments/assets/328193e7-cd44-461b-ba2e-4fad9a1ecd3f)
